title: Strata 

description: >
  Replace the text here <br />
  with a terse description. <br />
  Be sure to add the &lt;br /&gt;
baseurl: "" 
url: "http://yourdomain.com"

twitter_username:     example
github_username:      example
linkedin_username:    example
#google_plus_username: example
#facebook_username:    example
#dribbble_username:    example
email: your-email@domain.com 
