title: The Wandering IT Consultant 

description: >
  Ohai! Welcome to my blog.<br />
  Expect nothing but rambling.<br />
  All opinions are my own.

url: "http://blog.jerryaldrichiii.com"

twitter_username:     jerryaldrichiii
github_username:      jerryaldrichiii
linkedin_username:    jerryaldrichiii
email: me@jerryaldrichiii.com 
